includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.3
  extra_param:
    - 16
    - 1
train:
  max_epoch: 200
  lr: 0.001
  mile_stones:
    - 150
log_file: default
