includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.25    # causal ratio
  extra_param:
    - 1     # additional loss control
train:
  max_epoch: 200
  lr: 1e-3
  mile_stones: [150]


