includes:
  - base.yaml
model:
  model_name: CIGAGIN
ood:
  ood_alg: CIGA
  ood_param: 0.6
  extra_param:
    - 1
    - 0.5
train:
  max_epoch: 100
  lr: 0.001
  mile_stones:
    - 300
  train_bs: 128
  val_bs: 128
  test_bs: 128
log_file: default
